/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hridaya;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author vigne
 */
public class AddPatient extends javax.swing.JFrame {
    String username,date,time,id;

    /**
     * Creates new form AddPatient
     */
    public AddPatient() {
        initComponents();
    }
      public AddPatient(String username,String date,String time) {
          this.username=username;
          this.date=date;
          this.time=time;
          initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        lbl_back = new javax.swing.JLabel();
        lbl_home = new javax.swing.JLabel();
        lbl_logout = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        p_phno = new javax.swing.JTextField();
        p_email = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        p_insurance = new javax.swing.JTextField();
        p_age = new javax.swing.JTextField();
        p_bg = new javax.swing.JTextField();
        p_sex = new javax.swing.JComboBox<>();
        p_name = new javax.swing.JTextField();
        BTN_NEXT = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        p_weight = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        p_height = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        p_occ = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        p_hno = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        p_street = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        p_city = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        p_dob = new com.github.lgooddatepicker.components.DatePicker();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 153, 0));
        jPanel1.setMinimumSize(new java.awt.Dimension(1360, 750));
        jPanel1.setPreferredSize(new java.awt.Dimension(1360, 750));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 153, 51));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("PATIENT DETAILS");

        lbl_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/back arrow.png"))); // NOI18N
        lbl_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_backMouseClicked(evt);
            }
        });

        lbl_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/home_1.png"))); // NOI18N
        lbl_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_homeMouseClicked(evt);
            }
        });

        lbl_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/power off.png"))); // NOI18N
        lbl_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_logoutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lbl_back)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 376, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(519, 519, 519)
                .addComponent(lbl_home)
                .addGap(39, 39, 39)
                .addComponent(lbl_logout)
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_logout)
                    .addComponent(jLabel15)
                    .addComponent(lbl_back)
                    .addComponent(lbl_home))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1350, 70));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 0));
        jLabel3.setText("NAME");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 153, 0));
        jLabel4.setText("AGE");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, -1, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 153, 0));
        jLabel5.setText("SEX");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, -1, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 153, 0));
        jLabel6.setText("BLOODGROUP");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, -1, 20));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 153, 0));
        jLabel8.setText("PHONE NUMBER");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 210, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 153, 0));
        jLabel9.setText("EMAIL");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 250, -1, -1));
        jPanel1.add(p_phno, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 210, 220, -1));

        p_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_emailActionPerformed(evt);
            }
        });
        jPanel1.add(p_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 250, 220, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 153, 0));
        jLabel18.setText("INSURANCE ID");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 290, -1, -1));
        jPanel1.add(p_insurance, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 290, 220, -1));
        jPanel1.add(p_age, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, 240, 20));
        jPanel1.add(p_bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 370, 240, 20));

        p_sex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MALE", "FEMALE", "OTHERS" }));
        p_sex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_sexActionPerformed(evt);
            }
        });
        jPanel1.add(p_sex, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, 240, 20));
        jPanel1.add(p_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, 240, -1));

        BTN_NEXT.setText("SUBMIT");
        BTN_NEXT.setBackground(new java.awt.Color(255, 102, 51));
        BTN_NEXT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BTN_NEXT.setForeground(new java.awt.Color(255, 255, 255));
        BTN_NEXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_NEXTActionPerformed(evt);
            }
        });
        jPanel1.add(BTN_NEXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 650, 130, 30));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 153, 0));
        jLabel26.setText("WEIGHT");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 170, -1, -1));
        jPanel1.add(p_weight, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 170, 220, -1));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 153, 0));
        jLabel27.setText("HEIGHT");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, -1, -1));
        jPanel1.add(p_height, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 240, 20));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 153, 0));
        jLabel28.setText("OCCUPATION");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, -1, 20));
        jPanel1.add(p_occ, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, 240, 20));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 153, 51));
        jLabel11.setText("HOUSE NUMBER");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 330, 210, -1));

        p_hno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_hnoActionPerformed(evt);
            }
        });
        jPanel1.add(p_hno, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 330, 220, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 153, 51));
        jLabel24.setText("STREET");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 370, 210, -1));

        p_street.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_streetActionPerformed(evt);
            }
        });
        jPanel1.add(p_street, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 370, 220, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 153, 51));
        jLabel25.setText("CITY");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 410, 210, -1));

        p_city.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_cityActionPerformed(evt);
            }
        });
        jPanel1.add(p_city, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 410, 220, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 153, 0));
        jLabel7.setText("DOB");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, -1, 20));
        jPanel1.add(p_dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 410, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_backMouseClicked
        new frontDeskAppointment(username,date,time).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_backMouseClicked

    private void lbl_homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_homeMouseClicked
        new frontDesk(username,date,time).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_homeMouseClicked

    private void lbl_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_logoutMouseClicked
        String connectString="jdbc:mysql://localhost:3307/hospitalms?zeroDateTimeBehavior=convertToNull";
        Connection con = null;

        try {
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection(connectString,"root","");
            Statement st=con.createStatement();
            String qr="update login SET logged = '0' WHERE username = '"+username+"'";
            st.executeUpdate(qr);
            SimpleDateFormat dateformat1 = new SimpleDateFormat("HH:mm:ss");
            String timeout=dateformat1.format(Calendar.getInstance().getTime());
            String qt="update log_times SET logout_time = '"+timeout+"' WHERE id = '"+username+ "' AND date_login = '"+date+"' and login_time = '"+time+"'";
            st.executeUpdate(qt);
            con.close();

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
        finally
        {
            new Login().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_lbl_logoutMouseClicked

    private void p_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p_emailActionPerformed

    private void p_sexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_sexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p_sexActionPerformed

    private void BTN_NEXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_NEXTActionPerformed
        setBackground(Color.orange);
        String name=p_name.getText();
        //String pass=D_pass.getText();
        String houseno=p_hno.getText();
        int age=Integer.parseInt(p_age.getText());
        String sex= p_sex.getItemAt(p_sex.getSelectedIndex());
       String weight=p_weight.getText();
       String height=p_height.getText();
        String bg=p_bg.getText();
        //int consultation=Integer.parseInt(D_consultation.getText());
        String insurance=p_insurance.getText();
        String phno=p_phno.getText();
        String email=p_email.getText();
        String street=p_street.getText();
        String city=p_city.getText();
       String occ=p_occ.getText();
       String dob=p_dob.getDate().toString();

        String connectString="jdbc:mysql://localhost:3307/hospitalms?zeroDateTimeBehavior=convertToNull";
        Connection con = null;

        try {
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection(connectString,"root","");
            Statement st=con.createStatement();
            String qr="select * from patient_info";
            ResultSet rs=st.executeQuery(qr);

            while(rs.next())
            {
                id=rs.getString("p_id");
            }
            if(id==null)
            {
                // JOptionPane.showMessageDialog(null, "null id","null", 2);
                id="P1";
            }
            else
            {
                int i=Integer.parseInt(id.substring(1));
                i++;
                id="P"+i;
            }
            String qt="INSERT INTO PATIENT_INFO VALUES('"+id+"','"+name+"','"+age+"','"+sex+"','"+weight+"','"+height+"','"+occ+"','"+bg+"','"+insurance+"','"+dob+"','0')";
            st.executeUpdate(qt);
           // String qt1="INSERT INTO CONSULTING_TIME VALUES('"+id+"','"+workd+"','"+start+"','"+noh+"')";
           // st.executeUpdate(qt1);
            String qt2="INSERT INTO CONTACT_INFO VALUES('"+id+"','"+phno+"','"+null+"','"+email+"','"+houseno+"','"+street+"','"+city+"')";
            st.executeUpdate(qt2);
          //  String qt3="INSERT INTO QUALIFICATION VALUES('"+id+"','"+bachelors+"','"+masters+"','"+null+"','"+phd+"')";
            //st.executeUpdate(qt3);
            //String qt4="INSERT INTO LOGIN VALUES('"+id+"','"+pass+"','doctor','0')";
            //st.executeUpdate(qt4);
            con.close();

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
        finally
        {
            new frontDeskAppointment(username,date,time).setVisible(true);
            this.dispose();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_BTN_NEXTActionPerformed

    private void p_hnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_hnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p_hnoActionPerformed

    private void p_streetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_streetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p_streetActionPerformed

    private void p_cityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_cityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p_cityActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddPatient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_NEXT;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_back;
    private javax.swing.JLabel lbl_home;
    private javax.swing.JLabel lbl_logout;
    private javax.swing.JTextField p_age;
    private javax.swing.JTextField p_bg;
    private javax.swing.JTextField p_city;
    private com.github.lgooddatepicker.components.DatePicker p_dob;
    private javax.swing.JTextField p_email;
    private javax.swing.JTextField p_height;
    private javax.swing.JTextField p_hno;
    private javax.swing.JTextField p_insurance;
    private javax.swing.JTextField p_name;
    private javax.swing.JTextField p_occ;
    private javax.swing.JTextField p_phno;
    private javax.swing.JComboBox<String> p_sex;
    private javax.swing.JTextField p_street;
    private javax.swing.JTextField p_weight;
    // End of variables declaration//GEN-END:variables
}
