/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hridaya;

import java.awt.Color;
import hridaya.BCrypt;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author vigne
 */
public class Diagnose extends javax.swing.JFrame {
    String username,date,time,pid,did,aid;

    /**
     * Creates new form Diagnose
     */
    public Diagnose() {
        initComponents();
    }
     public Diagnose(String username,String date,String time, String aid,String pid,String did) {
         this.username=username;
         this.date=date;
         this.time=time;
         this.pid=pid;
         this.did=did;
         this.aid=aid;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        lbl_back = new javax.swing.JLabel();
        lbl_home = new javax.swing.JLabel();
        lbl_logout = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        p_age = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        p_weight = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        p_cond = new javax.swing.JTextField();
        BTN_NEXT = new javax.swing.JButton();
        p_id = new javax.swing.JLabel();
        p_name = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        p_height = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        p_care = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        p_hist = new javax.swing.JTextArea();
        jLabel26 = new javax.swing.JLabel();
        p_operate = new javax.swing.JCheckBox();
        p_admit = new javax.swing.JCheckBox();
        dis_date = new com.github.lgooddatepicker.components.DatePicker();
        admit_date = new com.github.lgooddatepicker.components.DatePicker();
        jLabel30 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 153, 0));
        jPanel1.setMinimumSize(new java.awt.Dimension(1360, 750));
        jPanel1.setPreferredSize(new java.awt.Dimension(1360, 750));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 153, 51));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("DOCTOR DETAILS");

        lbl_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/back arrow.png"))); // NOI18N
        lbl_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_backMouseClicked(evt);
            }
        });

        lbl_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/home_1.png"))); // NOI18N
        lbl_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_homeMouseClicked(evt);
            }
        });

        lbl_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/power off.png"))); // NOI18N
        lbl_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_logoutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lbl_back)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 382, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(519, 519, 519)
                .addComponent(lbl_home)
                .addGap(39, 39, 39)
                .addComponent(lbl_logout)
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_logout)
                    .addComponent(jLabel15)
                    .addComponent(lbl_back)
                    .addComponent(lbl_home))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1350, 70));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 0));
        jLabel2.setText("AGE");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 140, -1));

        p_age.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        p_age.setForeground(new java.awt.Color(255, 153, 0));
        p_age.setText("pATIENT aGE");
        jPanel1.add(p_age, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 153, 0));
        jLabel4.setText("HISTORY");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, -1, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 153, 0));
        jLabel6.setText("CARE");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, -1, 20));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 153, 0));
        jLabel8.setText("WEIGHT");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 210, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 153, 0));
        jLabel13.setText("CONDITION");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, -1, 20));

        p_weight.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        p_weight.setForeground(new java.awt.Color(255, 153, 0));
        p_weight.setText("HEIGHT");
        jPanel1.add(p_weight, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 210, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 153, 0));
        jLabel16.setText("SURGERY REQUIRED :");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 590, -1, -1));
        jPanel1.add(p_cond, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, 450, 30));

        BTN_NEXT.setBackground(new java.awt.Color(255, 102, 51));
        BTN_NEXT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BTN_NEXT.setForeground(new java.awt.Color(255, 255, 255));
        BTN_NEXT.setText("SUBMIT");
        BTN_NEXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_NEXTActionPerformed(evt);
            }
        });
        jPanel1.add(BTN_NEXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 650, 130, 30));

        p_id.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        p_id.setForeground(new java.awt.Color(255, 153, 0));
        p_id.setText("p_id");
        jPanel1.add(p_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, -1, -1));

        p_name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        p_name.setForeground(new java.awt.Color(255, 153, 0));
        p_name.setText("Patient name");
        jPanel1.add(p_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, -1, -1));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 153, 0));
        jLabel28.setText("HEIGHT");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 170, -1, -1));

        p_height.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        p_height.setForeground(new java.awt.Color(255, 153, 0));
        p_height.setText("HEIGHT");
        jPanel1.add(p_height, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 170, -1, -1));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 153, 0));
        jLabel27.setText("NAME");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, -1, -1));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 153, 0));
        jLabel29.setText("P ID");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, -1, -1));

        p_care.setColumns(20);
        p_care.setRows(5);
        jScrollPane1.setViewportView(p_care);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, 450, 110));

        p_hist.setColumns(20);
        p_hist.setRows(5);
        jScrollPane2.setViewportView(p_hist);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, 450, -1));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 153, 0));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("TO");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 547, 30, 20));

        p_operate.setText("YES");
        jPanel1.add(p_operate, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 580, -1, -1));

        p_admit.setText("YES");
        p_admit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_admitActionPerformed(evt);
            }
        });
        p_admit.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                p_admitPropertyChange(evt);
            }
        });
        jPanel1.add(p_admit, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 540, -1, -1));
        jPanel1.add(dis_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 540, 180, 30));
        jPanel1.add(admit_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 540, 180, 30));

        jLabel30.setText("ADMIT PATIENT : ");
        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 153, 0));
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 550, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_backMouseClicked
        new DocAppointment(username,date,time).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_backMouseClicked

    private void lbl_homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_homeMouseClicked
        new DoctorMain(username,date,time).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_homeMouseClicked

    private void lbl_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_logoutMouseClicked
        String connectString="jdbc:mysql://localhost:3307/hospitalms?zeroDateTimeBehavior=convertToNull";
        Connection con = null;

        try {
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection(connectString,"root","");
            Statement st=con.createStatement();
            String qr="update login SET logged = '0' WHERE username = '"+username+"'";
            st.executeUpdate(qr);
            SimpleDateFormat dateformat1 = new SimpleDateFormat("HH:mm:ss");
            String timeout=dateformat1.format(Calendar.getInstance().getTime());
            String qt="update log_times SET logout_time = '"+timeout+"' WHERE id = '"+username+ "' AND date_login = '"+date+"' and login_time = '"+time+"'";
            st.executeUpdate(qt);
            con.close();

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
        finally
        {
            new Login().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_lbl_logoutMouseClicked

    private void BTN_NEXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_NEXTActionPerformed
        setBackground(Color.orange);
       String cond=p_cond.getText();
       String hist=p_hist.getText();
       String care=p_care.getText();
        String connectString="jdbc:mysql://localhost:3307/hospitalms?zeroDateTimeBehavior=convertToNull";
        Connection con = null;

        try {
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection(connectString,"root","");
            Statement st=con.createStatement();
            String qr="insert into diagnosis values ('"+aid+"','"+did+"','"+cond+"','"+hist+"','"+care+"')";
            st.executeUpdate(qr);
            if(p_admit.isSelected())
            {
                 String qr1="insert into appointment_room values ('"+aid+"','R1','Regular','"+admit_date.getDate().toString()+"','"+dis_date.getDate().toString()+"','0','0')";
            st.executeUpdate(qr1);
               qr1="UPDATE APPOINTMENTS SET IS_ADMIT='1' WHERE APPOINTMENT_ID='"+aid+"'";
                st.executeUpdate(qr1);
            }
            if(p_operate.isSelected())
            {
                String q="SELECT * FROM APPOINTMENT_OPERATION";
                ResultSet rs=st.executeQuery(q);
                String i=null,id=null;
                while(rs.next())
                {
                    i=rs.getString("operation_id");
                }
                if(i==null)
                {
                    id="O1";
                }
                else
                {
                    int k=Integer.parseInt(i.substring(2));
                    k++;
                    id="O"+k;
                }
                String query="INSERT INTO APPOINTMENT_OPERATION VALUES ('"+aid+"','"+id+"','1','"+cond+"','0','0','0')";
                st.executeUpdate(query);
                query="UPDATE APPOINTMENTS SET IS_OPERATE='1' WHERE APPOINTMENT_ID='"+aid+"'";
                st.executeUpdate(query);
                
            }
            con.close();

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
        finally
        {
            new DocAppointment(username,date,time).setVisible(true);
            this.dispose();
        }
    

        // TODO add your handling code here:
    }//GEN-LAST:event_BTN_NEXTActionPerformed

    private void p_admitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_admitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p_admitActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
         String connectString="jdbc:mysql://localhost:3307/hospitalms?zeroDateTimeBehavior=convertToNull";
        Connection con = null;

        try {
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection(connectString,"root","");
            Statement st=con.createStatement();
            String qr="select * from patient_info where p_id = '"+pid+"'";
            ResultSet rs=st.executeQuery(qr);
            if(rs.next())
            {
            p_name.setText(rs.getString("name"));
            p_id.setText(rs.getString("p_id"));
            p_weight.setText(rs.getString("weight"));
            p_height.setText(rs.getString("height"));
            p_age.setText(rs.getString("age"));
            }
            con.close();
        
         } catch (ClassNotFoundException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_formWindowOpened

    private void p_admitPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_p_admitPropertyChange
       
    }//GEN-LAST:event_p_admitPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Diagnose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Diagnose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Diagnose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Diagnose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Diagnose().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_NEXT;
    private com.github.lgooddatepicker.components.DatePicker admit_date;
    private com.github.lgooddatepicker.components.DatePicker dis_date;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_back;
    private javax.swing.JLabel lbl_home;
    private javax.swing.JLabel lbl_logout;
    private javax.swing.JCheckBox p_admit;
    private javax.swing.JLabel p_age;
    private javax.swing.JTextArea p_care;
    private javax.swing.JTextField p_cond;
    private javax.swing.JLabel p_height;
    private javax.swing.JTextArea p_hist;
    private javax.swing.JLabel p_id;
    private javax.swing.JLabel p_name;
    private javax.swing.JCheckBox p_operate;
    private javax.swing.JLabel p_weight;
    // End of variables declaration//GEN-END:variables
}
