/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hridaya;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author vigne
 */
public class Salary extends javax.swing.JFrame {
    int ctc,gross,net,tax1,pf1;
    double pfp,pf,tax;
    String id,date,time,username;

    /**
     * Creates new form Salary
     */
    public Salary() {
        initComponents();
    }

    Salary(String id,String username, String date, String time) {
       // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
       this.id=id;
       this.username=username;
       this.date=date;
       this.time=time;
       initComponents();
       lbl_id.setText(id);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        lbl_id = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_pfp = new javax.swing.JTextField();
        txt_pf = new javax.swing.JTextField();
        txt_net = new javax.swing.JTextField();
        txt_gross = new javax.swing.JTextField();
        txt_income = new javax.swing.JTextField();
        txt_ctc = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        btn_submit = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 153, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 153, 51));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("SALARY INFO");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(475, 475, 475)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 70));

        lbl_id.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_id.setForeground(new java.awt.Color(255, 153, 0));
        jPanel1.add(lbl_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 110, -1, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 153, 0));
        jLabel4.setText("INCOME TAX");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, 200, 20));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 153, 0));
        jLabel8.setText("PROVIDENT FUND %");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 153, 0));
        jLabel9.setText("PROVIDENT FUND AMOUNT");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, 230, 20));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 153, 0));
        jLabel13.setText("GROSS SALARY");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, -1, 20));

        txt_pfp.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txt_pfpCaretUpdate(evt);
            }
        });
        txt_pfp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pfpActionPerformed(evt);
            }
        });
        jPanel1.add(txt_pfp, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 200, 240, -1));

        txt_pf.setEditable(false);
        txt_pf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pfActionPerformed(evt);
            }
        });
        jPanel1.add(txt_pf, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 240, 240, 20));

        txt_net.setEditable(false);
        jPanel1.add(txt_net, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 360, 240, -1));

        txt_gross.setEditable(false);
        jPanel1.add(txt_gross, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 280, 240, -1));

        txt_income.setEditable(false);
        jPanel1.add(txt_income, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 320, 240, -1));

        txt_ctc.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txt_ctcCaretUpdate(evt);
            }
        });
        jPanel1.add(txt_ctc, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 150, 240, -1));

        jLabel22.setBackground(new java.awt.Color(255, 153, 0));
        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 153, 0));
        jLabel22.setText("NET SALARY");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, 130, 20));

        btn_submit.setBackground(new java.awt.Color(255, 102, 51));
        btn_submit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_submit.setForeground(new java.awt.Color(255, 255, 255));
        btn_submit.setText("CALCULATE");
        btn_submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_submitMouseClicked(evt);
            }
        });
        btn_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submitActionPerformed(evt);
            }
        });
        jPanel1.add(btn_submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 430, 130, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 153, 0));
        jLabel5.setText("COST TO COMPANY");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, -1, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 153, 0));
        jLabel6.setText("ID");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, -1, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_pfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pfActionPerformed

    private void btn_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submitActionPerformed
        setBackground(Color.orange);
         if(btn_submit.getText().equals("CALCULATE"))
        {
            ctc=Integer.parseInt(txt_ctc.getText());
         pfp=Double.parseDouble(txt_pfp.getText());
         pf=(int)ctc*(pfp/100f);
         pf1=(int)pf;
         gross=(int)(ctc-pf);
         tax=0;
        if(ctc>1200000)
        {
            tax=(int)((30f/100f)*ctc);
        }
        else
        {
            tax=(int)((15f/100f)*ctc);
        }
        tax1=(int)tax;
        net=gross-tax1;
        txt_pf.setText(pf+"");
        txt_gross.setText(gross+"");
        txt_income.setText(tax+"");
        txt_net.setText(net+"");
        btn_submit.setText("SUBMIT");
        }
        else
         {
        
        String connectString="jdbc:mysql://localhost:3307/hospitalms?zeroDateTimeBehavior=convertToNull";
        Connection con = null;

        try {
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection(connectString,"root","");
            Statement st=con.createStatement();
            String qr="INSERT INTO SALARY_INFO VALUES('"+id+"','"+ctc+"','"+txt_pfp.getText()+"','"+gross+"','"+net+"','"+tax1+"','"+pf+"')";
            st.executeUpdate(qr);
            

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
        finally
        {
              new AddEmp(username,date,time).setVisible(true);
                this.dispose();
        }
         }

        // TODO add your handling code here:
    }//GEN-LAST:event_btn_submitActionPerformed

    private void txt_pfpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pfpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pfpActionPerformed

    private void txt_pfpCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txt_pfpCaretUpdate
        btn_submit.setText("CALCULATE");  
        
        
        
    }//GEN-LAST:event_txt_pfpCaretUpdate

    private void txt_ctcCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txt_ctcCaretUpdate
        btn_submit.setText("CALCULATE");        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ctcCaretUpdate

    private void btn_submitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_submitMouseClicked
       
     
    }//GEN-LAST:event_btn_submitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Salary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Salary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Salary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Salary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Salary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_submit;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JTextField txt_ctc;
    private javax.swing.JTextField txt_gross;
    private javax.swing.JTextField txt_income;
    private javax.swing.JTextField txt_net;
    private javax.swing.JTextField txt_pf;
    private javax.swing.JTextField txt_pfp;
    // End of variables declaration//GEN-END:variables
}
