/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hridaya;

/**
 *
 * @author vigne
 */
import java.awt.Color;
import hridaya.BCrypt;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
public class SignupDoc extends javax.swing.JFrame {
    String username,date,time;
    String id=null;
    String insurance=null;

    /**
     * Creates new form SignupDoc
     */
    public SignupDoc() {
        initComponents();
    }

    SignupDoc(String username, String date, String time) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        this.username=username;
        this.date=date;
        this.time=time;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        lbl_back = new javax.swing.JLabel();
        lbl_home = new javax.swing.JLabel();
        lbl_logout = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        D_hno = new javax.swing.JTextField();
        D_phno = new javax.swing.JTextField();
        D_smc = new javax.swing.JComboBox<>();
        D_email = new javax.swing.JTextField();
        D_yoe = new javax.swing.JTextField();
        D_pass = new javax.swing.JPasswordField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        D_workhour = new javax.swing.JTextField();
        D_consultation = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        D_insurance = new javax.swing.JTextField();
        D_bachelors = new javax.swing.JTextField();
        D_qyear = new javax.swing.JTextField();
        D_lic = new javax.swing.JTextField();
        D_spec = new javax.swing.JTextField();
        D_age = new javax.swing.JTextField();
        D_bg = new javax.swing.JTextField();
        D_sex = new javax.swing.JComboBox<>();
        D_name = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        D_masters = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        D_phd = new javax.swing.JTextField();
        BTN_NEXT = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        D_startt = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        D_workday = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        D_street = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        D_city = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1360, 800));
        setSize(new java.awt.Dimension(1360, 800));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 153, 0));
        jPanel1.setMinimumSize(new java.awt.Dimension(1360, 750));
        jPanel1.setPreferredSize(new java.awt.Dimension(1360, 750));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 153, 51));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("DOCTOR DETAILS");

        lbl_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/back arrow.png"))); // NOI18N
        lbl_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_backMouseClicked(evt);
            }
        });

        lbl_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/home_1.png"))); // NOI18N
        lbl_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_homeMouseClicked(evt);
            }
        });

        lbl_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/power off.png"))); // NOI18N
        lbl_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_logoutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lbl_back)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 382, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(519, 519, 519)
                .addComponent(lbl_home)
                .addGap(39, 39, 39)
                .addComponent(lbl_logout)
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_logout)
                    .addComponent(jLabel15)
                    .addComponent(lbl_back)
                    .addComponent(lbl_home))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1350, 70));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 0));
        jLabel2.setText("LICENSE NUMBER");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 140, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 0));
        jLabel3.setText("NAME");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 153, 0));
        jLabel4.setText("AGE");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, -1, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 153, 0));
        jLabel5.setText("SEX");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, -1, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 153, 0));
        jLabel6.setText("BLOODGROUP");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, -1, 20));

        jLabel7.setBackground(new java.awt.Color(255, 204, 0));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 153, 51));
        jLabel7.setText("STATE MEDICAL COUNCIL");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, -1, 20));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 153, 0));
        jLabel8.setText("PHONE NUMBER");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 210, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 153, 0));
        jLabel9.setText("EMAIL");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 250, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 153, 0));
        jLabel10.setText("QUALIFICATION YEAR");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 450, -1, 20));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 153, 51));
        jLabel11.setText("HOUSE NUMBER");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 500, 210, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 153, 0));
        jLabel12.setText("YEARS OF EXPERIENCE");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 290, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 153, 0));
        jLabel13.setText("SPECIALIZATION");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, -1, 20));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 153, 0));
        jLabel14.setText("PASSWORD");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 170, -1, -1));

        D_hno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D_hnoActionPerformed(evt);
            }
        });
        jPanel1.add(D_hno, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 500, 220, -1));
        jPanel1.add(D_phno, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 210, 220, -1));

        D_smc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Andhra Pradesh Medical Council", "Arunachal Pradesh Medical Council", "Assam Council of Medical Regisration", "Bihar Medical Council", "Chattisgarh Medical Council", "Delhi Medical Council", "Goa Medical Council", "Gujarat Medical Council", "Haryana Medical Council", "Himanchal Pradesh Medical Council", "Jammu & Kashmir Medical Council", "Jharkhand Medical Council", "Karnataka Medical Council", "Travancore Cochin Medical Council", "Madhya Pradesh Medical Council", "Maharashtra Medical Council", "Maharashtra Medical Council", "Mizoram Medical Council", "Nagaland Medical Council", "Orissa Council of Medical Registration", "Punjab Medical Council", "Rajasthan Medical Council", "Sikkim Medical Council", "Tamil Nadu Medical Council", "Telangana State Medical Council", "Tripura State Medical Council ", "Uttar Pradesh Medical Council", "Uttarakhand Medical Council", "West Bengal Medical Council" }));
        D_smc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D_smcActionPerformed(evt);
            }
        });
        jPanel1.add(D_smc, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 410, 240, 20));

        D_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D_emailActionPerformed(evt);
            }
        });
        jPanel1.add(D_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 250, 220, -1));
        jPanel1.add(D_yoe, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 290, 220, -1));
        jPanel1.add(D_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 170, 220, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 153, 0));
        jLabel16.setText("WORKING HOURS");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 610, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 153, 0));
        jLabel17.setText("CONSULTING PRICE");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 340, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 153, 0));
        jLabel18.setText("INSURANCE ID");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 380, -1, -1));

        D_workhour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D_workhourActionPerformed(evt);
            }
        });
        jPanel1.add(D_workhour, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 610, 240, -1));
        jPanel1.add(D_consultation, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 340, 220, -1));

        jLabel20.setBackground(new java.awt.Color(255, 153, 0));
        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 153, 0));
        jLabel20.setText("BACHELORS");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 420, 130, -1));
        jPanel1.add(D_insurance, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 380, 220, -1));
        jPanel1.add(D_bachelors, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 420, 220, -1));
        jPanel1.add(D_qyear, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 450, 240, 20));
        jPanel1.add(D_lic, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 240, -1));
        jPanel1.add(D_spec, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, 240, -1));
        jPanel1.add(D_age, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, 240, -1));
        jPanel1.add(D_bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 370, 240, 20));

        D_sex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MALE", "FEMALE", "OTHERS" }));
        D_sex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D_sexActionPerformed(evt);
            }
        });
        jPanel1.add(D_sex, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, 240, 20));
        jPanel1.add(D_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, 240, -1));

        jLabel21.setBackground(new java.awt.Color(255, 153, 0));
        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 153, 0));
        jLabel21.setText("MASTERS");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 460, 130, -1));
        jPanel1.add(D_masters, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 460, 220, -1));

        jLabel22.setBackground(new java.awt.Color(255, 153, 0));
        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 153, 0));
        jLabel22.setText("PHD");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 490, 130, 20));
        jPanel1.add(D_phd, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 490, 240, 20));

        BTN_NEXT.setBackground(new java.awt.Color(255, 102, 51));
        BTN_NEXT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BTN_NEXT.setForeground(new java.awt.Color(255, 255, 255));
        BTN_NEXT.setText("NEXT");
        BTN_NEXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_NEXTActionPerformed(evt);
            }
        });
        jPanel1.add(BTN_NEXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 650, 130, 30));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 153, 0));
        jLabel19.setText("START TIME");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 570, -1, -1));

        D_startt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D_starttActionPerformed(evt);
            }
        });
        jPanel1.add(D_startt, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 570, 240, -1));

        jLabel23.setBackground(new java.awt.Color(255, 153, 0));
        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 153, 0));
        jLabel23.setText("WORKING DAYS (1-7)");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 530, 180, 20));
        jPanel1.add(D_workday, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 530, 240, 20));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 153, 51));
        jLabel24.setText("STREET");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 540, 210, -1));

        D_street.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D_streetActionPerformed(evt);
            }
        });
        jPanel1.add(D_street, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 540, 220, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 153, 51));
        jLabel25.setText("CITY");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 580, 210, -1));

        D_city.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D_cityActionPerformed(evt);
            }
        });
        jPanel1.add(D_city, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 580, 220, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void D_hnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D_hnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D_hnoActionPerformed

    private void D_smcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D_smcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D_smcActionPerformed

    private void D_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D_emailActionPerformed

    private void D_workhourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D_workhourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D_workhourActionPerformed

    private void D_sexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D_sexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D_sexActionPerformed

    private void lbl_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_backMouseClicked
        new Admin(username,date,time).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_backMouseClicked

    private void lbl_homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_homeMouseClicked
        new Admin(username,date,time).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_homeMouseClicked

    private void lbl_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_logoutMouseClicked
        String connectString="jdbc:mysql://localhost:3307/hospitalms?zeroDateTimeBehavior=convertToNull";
        Connection con = null;

        try {
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection(connectString,"root","");
            Statement st=con.createStatement();
            String qr="update login SET logged = '0' WHERE username = '"+username+"'";
            st.executeUpdate(qr);
            SimpleDateFormat dateformat1 = new SimpleDateFormat("HH:mm:ss");
            String timeout=dateformat1.format(Calendar.getInstance().getTime());
            String qt="update log_times SET logout_time = '"+timeout+"' WHERE id = '"+username+ "' AND date_login = '"+date+"' and login_time = '"+time+"'";
            st.executeUpdate(qt);
            con.close();

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
        finally
        {
            new Login().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_lbl_logoutMouseClicked

    private void BTN_NEXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_NEXTActionPerformed
        setBackground(Color.orange);
        String name=D_name.getText();
        String pass=BCrypt.hashpw(D_pass.getText(),BCrypt.gensalt(12));
        
        String houseno=D_hno.getText();
        int age=Integer.parseInt(D_age.getText());
        String sex= D_sex.getItemAt(D_sex.getSelectedIndex());
        String licno=D_lic.getText();
        String smc=D_smc.getItemAt(D_smc.getSelectedIndex());
        int year=Integer.parseInt(D_qyear.getText());
        String spec=D_spec.getText();
        String yoe=D_yoe.getText();
        String bg=D_bg.getText();
        int consultation=Integer.parseInt(D_consultation.getText());
        insurance=D_insurance.getText();
        String phno=D_phno.getText();
        String email=D_email.getText();
        String street=D_street.getText();
        String city=D_city.getText();
        String bachelors=D_bachelors.getText();
        String masters=D_masters.getText();
        String phd=D_phd.getText();
        int workd=Integer.parseInt(D_workday.getText());
        String start=D_startt.getText();
        int noh=Integer.parseInt(D_workhour.getText());
        
        String connectString="jdbc:mysql://localhost:3307/hospitalms?zeroDateTimeBehavior=convertToNull";
        Connection con = null;

        try {
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection(connectString,"root","");
            Statement st=con.createStatement();
            String qr="select * from doc_info";
            ResultSet rs=st.executeQuery(qr);
            
            while(rs.next())
            {
                id=rs.getString("doc_id");
            }
            if(id==null)
            {
               // JOptionPane.showMessageDialog(null, "null id","null", 2);
                id="D1";
            }
            else
            {
                int i=Integer.parseInt(id.substring(1));
                i++;
                id="D"+i;
            }
            String qt="INSERT INTO DOC_INFO VALUES('"+id+"','"+name+"','"+age+"','"+sex+"','"+licno+"','"+smc+"','"+year+"','"+spec+"','"+yoe+"','"+bg+"','"+consultation+"','"+insurance+"','1')";
            st.executeUpdate(qt);
             String qt1="INSERT INTO CONSULTING_TIME VALUES('"+id+"','"+workd+"','"+start+"','"+noh+"')";
            st.executeUpdate(qt1);
            String qt2="INSERT INTO CONTACT_INFO VALUES('"+id+"','"+phno+"','"+null+"','"+email+"','"+houseno+"','"+street+"','"+city+"')";
            st.executeUpdate(qt2);
               String qt3="INSERT INTO QUALIFICATION VALUES('"+id+"','"+bachelors+"','"+masters+"','"+null+"','"+phd+"')";
            st.executeUpdate(qt3);
            String qt4="INSERT INTO LOGIN VALUES('"+id+"','"+pass+"','doctor','0')";
            st.executeUpdate(qt4);
            con.close();
            
            

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
        finally
        {
            new EmergencyContact(id,insurance,username,date,time).setVisible(true);
            this.dispose();
        }
                                         
        
        
        
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_BTN_NEXTActionPerformed

    private void D_starttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D_starttActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D_starttActionPerformed

    private void D_streetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D_streetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D_streetActionPerformed

    private void D_cityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D_cityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D_cityActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignupDoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignupDoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignupDoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignupDoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignupDoc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_NEXT;
    private javax.swing.JTextField D_age;
    private javax.swing.JTextField D_bachelors;
    private javax.swing.JTextField D_bg;
    private javax.swing.JTextField D_city;
    private javax.swing.JTextField D_consultation;
    private javax.swing.JTextField D_email;
    private javax.swing.JTextField D_hno;
    private javax.swing.JTextField D_insurance;
    private javax.swing.JTextField D_lic;
    private javax.swing.JTextField D_masters;
    private javax.swing.JTextField D_name;
    private javax.swing.JPasswordField D_pass;
    private javax.swing.JTextField D_phd;
    private javax.swing.JTextField D_phno;
    private javax.swing.JTextField D_qyear;
    private javax.swing.JComboBox<String> D_sex;
    private javax.swing.JComboBox<String> D_smc;
    private javax.swing.JTextField D_spec;
    private javax.swing.JTextField D_startt;
    private javax.swing.JTextField D_street;
    private javax.swing.JTextField D_workday;
    private javax.swing.JTextField D_workhour;
    private javax.swing.JTextField D_yoe;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_back;
    private javax.swing.JLabel lbl_home;
    private javax.swing.JLabel lbl_logout;
    // End of variables declaration//GEN-END:variables
}
